"""Context Hygiene Compactor — shrinks bloated conversation history before
main-model inference, so local LLMs with limited effective-context can still
reason coherently.

Architecture rationale — see `docs/research/...` in the private repo for the
full design doc.  Summary:

  - Local LLMs (e.g. Qwen3-Coder-480B on Mac Studio) have effective agent
    context of ~20-40K tokens before attention degrades.  Hosted Claude
    tolerates much more because Anthropic pays the attention-compute cost.
  - Claude Code CLI tools were designed for hosted-LLM economics:
    ``Read`` dumps whole files, ``Bash`` dumps full stdout, etc.  For
    sessions of 5+ turns this quickly exceeds local effective context.
  - Solution: middleware that replaces bloated ``tool_result`` blocks with
    faithful summaries BEFORE they reach the main model.  Summaries are
    generated by a smaller curator model (e.g. gpt-oss:120b on the same
    fleet), cached by content hash (sticky across sessions), and marked
    explicitly so the agent knows what's compact vs verbatim.

Key invariants — DO NOT VIOLATE:

  1. **Cache stability.** Compacted prefix bytes must be identical across
     requests for the same underlying content, or we bust mlx's prefix
     cache and lose the 10-100× warm-turn speedup.  Enforced via:
       - Content-addressed cache (SHA-256 of raw content → summary)
       - Deterministic curator calls (temperature=0)
       - Sticky summaries (once cached, never regenerated until strategy
         version bumps)

  2. **Never compact cached prefix content.**  System prompt and tool
     definitions are pinned in the prefix cache.  Compacting them would
     bust the cache for every subsequent turn.  Only the message history
     (specifically: old tool_result blocks) is eligible.

  3. **Preserve recency.**  The last N turns (default 3) are passed
     through verbatim.  These are the model's active reasoning context
     and compacting them damages quality.

  4. **Preserve tool_use (assistant side).**  ``tool_use`` blocks inside
     assistant messages are the model's own output; compacting them
     breaks trace continuity and may confuse the agent about its own
     prior decisions.  Only tool RESULTS (the user-role reply that
     follows a tool_use) are compactable.

  5. **Fail open.**  If the curator fails or times out, pass the
     original content through unchanged and log the failure.  Bad
     compaction is worse than no compaction.

# EXTRACTION SEAM (recorded 2026-04-24):
# - Fleet-manager dependencies (at runtime, not import time):
#     * ``CuratorSelector.select()`` reads ``NodeState``-like objects but only
#       touches ``.ollama.models_loaded[].name`` and ``.node_id`` — duck-typed.
#       Extraction would replace with any shape that exposes that surface.
#     * The ``curator_selector`` + ``resolve_curator_context`` callbacks are
#       LATE-BOUND — constructed by ``app.py`` when the compactor is wired up.
#       The module itself has no fleet_manager imports.
#     * Lazy import inside ``CuratorSelector._eligible()`` for
#       ``fleet_manager.server.model_knowledge`` — would need to be
#       parameterized or inlined on extraction.
# - External dependencies: stdlib + sqlite3 + logging.
# - Public surface to preserve if extracted:
#     STRATEGY_VERSION, STRATEGIES_BY_TOOL (Strategy dataclass + tool→strategy map)
#     CuratorProtocol (Protocol), OllamaCurator (example impl)
#     SummaryCache (SQLite-backed)
#     CompactionReport, ContextCompactor, CuratorSelector
# - Critical invariant: byte-stable summaries across runs.  See module
#   docstring invariant (1).  Any extraction MUST preserve the
#   deterministic-curator-call + content-hash-keyed-cache contract.
# - Medium coupling; extract together with ``context_management.py`` as a
#   layer-1 + layer-2 pair for a cohesive "context management" package.
#   Remove the ``model_knowledge`` import (or make it a pluggable predicate)
#   to sever the last fleet-manager tie.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import json
import logging
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

logger = logging.getLogger(__name__)


# Strategy version — bump when a strategy's prompt or behavior changes,
# invalidating old cached summaries.  Cache entries under older versions
# become stale and regenerate on next use.
STRATEGY_VERSION = "v1-2026-04-23"


# ----------------------------------------------------------------------------
# Curator interface — pluggable LLM for summary generation
# ----------------------------------------------------------------------------


class CuratorProtocol(Protocol):
    """A callable that takes (prompt_text, max_output_tokens) → summary_text.

    The curator should be deterministic (temperature=0) and fast.
    Implementations should handle their own timeouts and retries.
    """

    async def summarize(
        self, system: str, prompt: str, max_tokens: int = 512, timeout_s: float = 60.0,
    ) -> str | None:
        """Return the summary text, or None on failure/timeout."""
        ...


class OllamaCurator:
    """Curator backed by an Ollama model (e.g. gpt-oss:120b).

    Reuses the herd's existing Ollama client infrastructure.  Uses
    non-streaming chat.  Deterministic via temperature=0.

    The ``model`` passed at construction time is the fallback/default.
    Callers can override per-summarise call when using dynamic curator
    selection (see ``CuratorSelector``).
    """

    def __init__(self, ollama_client, model: str):
        self._ollama = ollama_client
        self.model = model

    async def summarize(
        self,
        system: str,
        prompt: str,
        max_tokens: int = 512,
        timeout_s: float = 60.0,
        *,
        model: str | None = None,
    ) -> str | None:
        effective_model = model or self.model
        body = {
            "model": effective_model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
            "stream": False,
            "options": {
                "temperature": 0.0,  # determinism for cache stability
                "top_p": 1.0,
                "num_predict": max_tokens,
            },
        }
        try:
            resp = await asyncio.wait_for(self._ollama.chat(body), timeout=timeout_s)
        except TimeoutError:
            logger.warning(f"Curator {effective_model} timed out after {timeout_s}s")
            return None
        except Exception as exc:  # noqa: BLE001 — curator failure must fail-open
            logger.warning(
                f"Curator {effective_model} failed: {type(exc).__name__}: {exc}"
            )
            return None
        try:
            return resp["message"]["content"].strip()
        except (KeyError, AttributeError, TypeError):
            logger.warning(
                f"Curator {effective_model} returned unparseable response"
            )
            return None


# ----------------------------------------------------------------------------
# Curator selector — pick the best available model for summary work
# ----------------------------------------------------------------------------


@dataclass
class CuratorCandidate:
    """A model considered for curator duty, with its ranking inputs."""

    model: str
    node_id: str
    params_b: float
    is_pinned: bool
    recent_requests: int  # in the idle window
    score: float = 0.0


class CuratorSelector:
    """Pick a curator model based on current fleet state.

    Policy (highest-wins ranking):

      1. Candidate must be a hot (``models_loaded``) instruct-capable
         model — categories GENERAL / CODING / REASONING — with params
         >= ``min_params_b``.  Smaller models produce unreliable
         summaries; we'd rather skip compaction than use them.

      2. Activity penalty: each request in the last ``idle_window_s``
         subtracts from the score.  An idle model ranks far above a
         busy one, regardless of quality.

      3. Pinned bonus: pinned models are reliably hot across sessions
         (won't evict), so they're preferred for repeated curator work
         when idle.

      4. Quality tiebreaker: larger params → better summaries.

    If no hot candidate is idle enough, returns the configured default
    model (which the curator will cold-load — only acceptable because
    the default is usually itself pinned + hot).  If even the default
    has activity above threshold, returns ``None`` and the compactor
    fails-open (no compaction this request).
    """

    def __init__(
        self,
        *,
        default_model: str,
        idle_window_s: int = 120,
        min_params_b: float = 7.0,
        activity_penalty_per_request: float = 100.0,
        pinned_bonus: float = 20.0,
    ):
        self.default_model = default_model
        self.idle_window_s = idle_window_s
        self.min_params_b = min_params_b
        self.activity_penalty_per_request = activity_penalty_per_request
        self.pinned_bonus = pinned_bonus

    def _eligible(self, model_name: str) -> tuple[bool, float]:
        """Return (eligible?, params_b).  Imported lazily to avoid cycles."""
        from fleet_manager.server.model_knowledge import (
            ModelCategory,
            classify_model,
            lookup_model,
        )

        category = classify_model(model_name)
        # Instruct-capable text categories are all fine as curators.  VISION
        # models (gemma3, llama3.2-vision) are still instruct LLMs that
        # handle text summarization; their vision capability is just extra.
        # Excluded: VISION_EMBEDDING (encoder only), IMAGE (generation).
        if category in {
            ModelCategory.VISION_EMBEDDING,
            ModelCategory.IMAGE,
        }:
            return False, 0.0
        spec = lookup_model(model_name)
        params_b = spec.params_b if spec else 0.0
        if params_b < self.min_params_b:
            return False, params_b
        return True, params_b

    def select(
        self,
        *,
        nodes: list,
        env_pins: list[str],
        per_node_pins: dict[str, list[str]],
        activity: dict[str, int],
    ) -> str | None:
        """Pick the best curator model, or None to skip compaction.

        ``nodes`` is a list of NodeState.  ``activity`` is the trace
        store's request-count-by-model over ``idle_window_s``.
        """
        # Gather hot candidates across the fleet
        candidates: list[CuratorCandidate] = []
        seen: set[tuple[str, str]] = set()
        for node in nodes:
            if not node.ollama:
                continue
            node_pins = set(per_node_pins.get(node.node_id, []))
            for lm in node.ollama.models_loaded:
                key = (node.node_id, lm.name)
                if key in seen:
                    continue
                seen.add(key)
                ok, params_b = self._eligible(lm.name)
                if not ok:
                    continue
                is_pinned = lm.name in env_pins or lm.name in node_pins
                recent = activity.get(lm.name, 0)
                score = (
                    params_b  # quality tiebreaker (1-500 range)
                    - recent * self.activity_penalty_per_request
                    + (self.pinned_bonus if is_pinned else 0.0)
                )
                candidates.append(CuratorCandidate(
                    model=lm.name, node_id=node.node_id,
                    params_b=params_b, is_pinned=is_pinned,
                    recent_requests=recent, score=score,
                ))

        if candidates:
            # Pick the highest-scoring eligible candidate
            candidates.sort(key=lambda c: c.score, reverse=True)
            best = candidates[0]
            # Only accept if activity is low enough — a heavily-hit model
            # beats out quality only if every candidate is busy.
            if best.recent_requests == 0:
                return best.model
            # All candidates have activity — fall through to default policy

        # Fallback: configured default.  Check if the default is itself
        # currently saturated; if so, skip compaction this request.
        default_activity = activity.get(self.default_model, 0)
        # Threshold: > 3 requests in the idle window = "busy enough to skip"
        if default_activity > 3:
            return None
        return self.default_model


# ----------------------------------------------------------------------------
# Strategies — content-type-specific compaction prompts
# ----------------------------------------------------------------------------


@dataclass
class Strategy:
    """A compaction strategy: what prompt to send the curator, plus policy."""

    name: str
    system_prompt: str
    user_prompt_template: str  # {content} gets replaced with raw content
    max_output_tokens: int
    # Only compact if the original is larger than this — below, not worth it.
    min_bloat_tokens: int


# Summarize arbitrary file content: preserve identifiers/signatures, drop body.
STRATEGY_READ = Strategy(
    name="read",
    system_prompt=(
        "You are a code summarization assistant.  Another AI needs to know "
        "what's in a file without reading every line.  Extract:\n"
        "  - Public symbols (classes, functions) with their signatures\n"
        "  - Imports and external dependencies\n"
        "  - 1-2 sentences describing the file's purpose\n"
        "  - Any notable constants, patterns, or side effects\n"
        "Preserve EXACTLY: identifier names, file paths, numeric constants, "
        "error message text.  Drop: implementation details, docstrings unless "
        "they add unique info, comments.\n"
        "Respond with the summary only, no preamble."
    ),
    user_prompt_template="File content to summarize:\n\n{content}",
    max_output_tokens=400,
    min_bloat_tokens=1500,
)

# Summarize shell command output: keep first+last lines + exit status.
STRATEGY_BASH = Strategy(
    name="bash",
    system_prompt=(
        "You are summarizing shell command output for another AI.  Keep:\n"
        "  - Exit code (if visible)\n"
        "  - The first 3 lines of output\n"
        "  - The last 3 lines of output\n"
        "  - Any error messages VERBATIM\n"
        "  - Any absolute file paths VERBATIM\n"
        "Drop: repetitive progress lines, log noise, whitespace.\n"
        "Respond with the summary only, no preamble."
    ),
    user_prompt_template="Shell output to summarize:\n\n{content}",
    max_output_tokens=300,
    min_bloat_tokens=800,
)

# Summarize webfetch output (HTML→markdown dump).
STRATEGY_WEBFETCH = Strategy(
    name="webfetch",
    system_prompt=(
        "You are summarizing a web page's content for another AI.  Extract:\n"
        "  - Main topic (1 sentence)\n"
        "  - Key facts, figures, identifiers\n"
        "  - Any code snippets VERBATIM\n"
        "  - URLs referenced\n"
        "Drop: navigation, ads, boilerplate, formatting fluff.\n"
        "Respond with the summary only, no preamble."
    ),
    user_prompt_template="Web page content to summarize:\n\n{content}",
    max_output_tokens=500,
    min_bloat_tokens=2000,
)


# Map from tool name → strategy.  Tools not listed pass through verbatim.
STRATEGIES_BY_TOOL: dict[str, Strategy] = {
    "Read": STRATEGY_READ,
    "Bash": STRATEGY_BASH,
    "WebFetch": STRATEGY_WEBFETCH,
}


# ----------------------------------------------------------------------------
# Summary cache — content-addressed, persistent across sessions
# ----------------------------------------------------------------------------


class SummaryCache:
    """SQLite-backed content-addressed summary cache.

    Key: (content_sha256, strategy_name, strategy_version).  Returning
    the SAME summary bytes for the SAME input content is what preserves
    mlx prefix-cache stability across sessions.

    Thread-safe for concurrent reads; writes are single-threaded via
    a connection-per-call pattern (SQLite's default-serialized mode).
    """

    def __init__(self, db_path: Path):
        self.db_path = db_path
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    def _conn(self) -> sqlite3.Connection:
        c = sqlite3.connect(self.db_path, timeout=5.0)
        c.row_factory = sqlite3.Row
        return c

    def _init_schema(self) -> None:
        with self._conn() as c:
            c.execute("""
                CREATE TABLE IF NOT EXISTS summaries (
                    content_hash TEXT NOT NULL,
                    strategy TEXT NOT NULL,
                    strategy_version TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    original_tokens INTEGER NOT NULL,
                    summary_tokens INTEGER NOT NULL,
                    curator_model TEXT NOT NULL,
                    created_at REAL NOT NULL,
                    hit_count INTEGER NOT NULL DEFAULT 0,
                    PRIMARY KEY (content_hash, strategy, strategy_version)
                )
            """)
            c.execute("""
                CREATE INDEX IF NOT EXISTS idx_summaries_created_at
                ON summaries(created_at)
            """)

    def get(
        self, content_hash: str, strategy: str, version: str = STRATEGY_VERSION,
    ) -> str | None:
        with self._conn() as c:
            row = c.execute(
                "SELECT summary FROM summaries "
                "WHERE content_hash = ? AND strategy = ? AND strategy_version = ?",
                (content_hash, strategy, version),
            ).fetchone()
            if row is None:
                return None
            # Bump hit count (best-effort; don't block caller on failure)
            with contextlib.suppress(sqlite3.OperationalError):
                c.execute(
                    "UPDATE summaries SET hit_count = hit_count + 1 "
                    "WHERE content_hash = ? AND strategy = ? AND strategy_version = ?",
                    (content_hash, strategy, version),
                )
            return row["summary"]

    def put(
        self,
        content_hash: str,
        strategy: str,
        summary: str,
        original_tokens: int,
        summary_tokens: int,
        curator_model: str,
        version: str = STRATEGY_VERSION,
    ) -> None:
        with self._conn() as c:
            c.execute(
                "INSERT OR REPLACE INTO summaries "
                "(content_hash, strategy, strategy_version, summary, "
                "original_tokens, summary_tokens, curator_model, created_at, hit_count) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)",
                (
                    content_hash, strategy, version, summary,
                    original_tokens, summary_tokens, curator_model, time.time(),
                ),
            )

    def stats(self) -> dict:
        """Cache size / hit distribution for dashboard exposure."""
        with self._conn() as c:
            row = c.execute(
                "SELECT COUNT(*) as n_entries, "
                "SUM(original_tokens) as total_original, "
                "SUM(summary_tokens) as total_summary, "
                "SUM(hit_count) as total_hits "
                "FROM summaries"
            ).fetchone()
            return {
                "entries": row["n_entries"] or 0,
                "total_original_tokens": row["total_original"] or 0,
                "total_summary_tokens": row["total_summary"] or 0,
                "total_hits": row["total_hits"] or 0,
            }


# ----------------------------------------------------------------------------
# Compactor — the main entry point
# ----------------------------------------------------------------------------


@dataclass
class CompactionReport:
    """What the compactor did on a single request.  Flows into traces."""

    triggered: bool = False
    tokens_before: int = 0
    tokens_after: int = 0
    compactions: list[dict] = field(default_factory=list)

    @property
    def ratio(self) -> float:
        if not self.tokens_before:
            return 1.0
        return self.tokens_after / self.tokens_before

    def to_dict(self) -> dict:
        return {
            "triggered": self.triggered,
            "tokens_before": self.tokens_before,
            "tokens_after": self.tokens_after,
            "ratio": round(self.ratio, 3),
            "compactions": list(self.compactions),
        }


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def _estimate_tokens(text: str) -> int:
    """Rough: 4 chars/token.  Good enough for budget decisions."""
    return max(1, len(text) // 4)


class ContextCompactor:
    """Server-side middleware that shrinks bloated conversation history.

    Stateless across requests except for the SummaryCache.  Safe to
    share a single instance across all requests — internal caching is
    SQLite-backed and thread-safe.
    """

    def __init__(
        self,
        curator: CuratorProtocol,
        cache: SummaryCache,
        *,
        budget_tokens: int = 20_000,
        preserve_last_turns: int = 3,
        curator_selector: CuratorSelector | None = None,
        resolve_curator_context=None,
    ):
        self.curator = curator
        self.cache = cache
        self.budget_tokens = budget_tokens
        self.preserve_last_turns = preserve_last_turns
        # Dynamic curator selection — optional.  When provided, the
        # selector is invoked once per ``maybe_compact`` call to pick
        # the best hot/idle model for summary work.  ``resolve_curator_context``
        # is a callable (sync or async) returning the kwargs the selector
        # needs (nodes/env_pins/per_node_pins/activity).  Kept as a
        # callback so the compactor doesn't need to know about the
        # registry / pin store / trace store directly.
        self.curator_selector = curator_selector
        self._resolve_curator_context = resolve_curator_context

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def maybe_compact(
        self, messages: list[dict],
        *,
        force_all: bool = False,
    ) -> tuple[list[dict], CompactionReport]:
        """Compact messages if they exceed the budget; otherwise pass through.

        Input: Anthropic-format messages (content may be string or block list).
        Output: (possibly-modified messages, report).

        Does NOT modify the input list in place.

        ``force_all``: when True, ignore each strategy's ``min_bloat_tokens``
        gate and try to compact EVERY eligible tool_result block regardless
        of size.  Used for session-level rescue: after Layer 1 mechanical
        clearing has run, if the total prompt is still huge, we want the
        LLM compactor to work on every remaining block — even small ones
        — to shrink as aggressively as possible.  Pre-inference 413 is the
        fallback if even force_all doesn't get us under budget.
        """
        report = CompactionReport()
        report.tokens_before = self._total_tokens(messages)

        if report.tokens_before <= self.budget_tokens:
            report.tokens_after = report.tokens_before
            return messages, report

        # Build a map of tool_use_id → tool_name by scanning assistant
        # messages.  Needed to classify tool_result blocks.
        tool_use_names = self._index_tool_uses(messages)

        # Identify which messages are eligible (preserve the last N turns).
        n_total = len(messages)
        preserved_start = max(0, n_total - self.preserve_last_turns * 2)
        # * 2 because each turn is user+assistant on average

        report.triggered = True
        out_messages: list[dict] = []

        # Resolve curator model ONCE per request.  This gives us a
        # stable choice across all summaries in this request, and lets
        # us bail out entirely when no suitable curator is available
        # (fail-open rather than queue behind real user traffic).
        curator_model = await self._pick_curator_model()
        if curator_model is None:
            logger.info(
                "Compactor: no eligible curator available — skipping "
                "compaction for this request (fail-open)",
            )
            report.tokens_after = report.tokens_before
            report.triggered = False
            return messages, report

        for i, msg in enumerate(messages):
            if i >= preserved_start:
                # Preserve verbatim — recent turns
                out_messages.append(msg)
                continue
            # Compactable range: look at content blocks for tool_results
            new_msg = await self._compact_message(
                msg, tool_use_names, report,
                curator_model=curator_model,
                force_all=force_all,
            )
            out_messages.append(new_msg)

        report.tokens_after = self._total_tokens(out_messages)
        return out_messages, report

    async def _pick_curator_model(self) -> str | None:
        """Ask the selector which model to use, or fall back to the default."""
        if self.curator_selector is None or self._resolve_curator_context is None:
            return getattr(self.curator, "model", None)
        try:
            ctx = self._resolve_curator_context()
            if asyncio.iscoroutine(ctx):
                ctx = await ctx
            return self.curator_selector.select(**ctx)
        except Exception as exc:  # noqa: BLE001 — selection must never crash a request
            logger.warning(
                f"Curator selection failed: {type(exc).__name__}: {exc}; "
                f"falling back to configured default",
            )
            return getattr(self.curator, "model", None)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _index_tool_uses(self, messages: list[dict]) -> dict[str, str]:
        """Walk messages, return {tool_use_id → tool_name} map."""
        out: dict[str, str] = {}
        for m in messages:
            if m.get("role") != "assistant":
                continue
            c = m.get("content")
            if not isinstance(c, list):
                continue
            for block in c:
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    tool_id = block.get("id")
                    tool_name = block.get("name")
                    if tool_id and tool_name:
                        out[tool_id] = tool_name
        return out

    def _total_tokens(self, messages: list[dict]) -> int:
        """Estimate total tokens across all messages."""
        total = 0
        for m in messages:
            c = m.get("content")
            if isinstance(c, str):
                total += _estimate_tokens(c)
            elif isinstance(c, list):
                for block in c:
                    if not isinstance(block, dict):
                        continue
                    if block.get("type") == "text":
                        total += _estimate_tokens(block.get("text") or "")
                    elif block.get("type") == "tool_use":
                        total += _estimate_tokens(
                            json.dumps(block.get("input") or {})
                        )
                    elif block.get("type") == "tool_result":
                        inner = block.get("content")
                        if isinstance(inner, str):
                            total += _estimate_tokens(inner)
                        elif isinstance(inner, list):
                            for sub in inner:
                                if (
                                    isinstance(sub, dict)
                                    and sub.get("type") == "text"
                                ):
                                    total += _estimate_tokens(sub.get("text") or "")
        return total

    async def _compact_message(
        self,
        msg: dict,
        tool_use_names: dict[str, str],
        report: CompactionReport,
        *,
        curator_model: str | None = None,
        force_all: bool = False,
    ) -> dict:
        """Walk a message's content blocks, compact tool_results if eligible."""
        content = msg.get("content")
        if not isinstance(content, list):
            return msg  # string content or unknown — pass through

        new_blocks: list[dict] = []
        changed = False
        for block in content:
            if (
                not isinstance(block, dict)
                or block.get("type") != "tool_result"
            ):
                new_blocks.append(block)
                continue
            # Classify via the corresponding tool_use
            tool_id = block.get("tool_use_id")
            tool_name = tool_use_names.get(tool_id or "")
            strategy = STRATEGIES_BY_TOOL.get(tool_name or "")
            if strategy is None:
                new_blocks.append(block)
                continue
            # Extract text payload
            raw_text = self._extract_text(block)
            if not raw_text:
                new_blocks.append(block)
                continue
            tok_before = _estimate_tokens(raw_text)
            # ``force_all`` mode: bypass the per-strategy min_bloat_tokens
            # gate.  Session-level rescue path — even small blocks get
            # summarised because the total prompt is already catastrophic
            # and we need to shrink everything we can.
            if not force_all and tok_before < strategy.min_bloat_tokens:
                new_blocks.append(block)
                continue
            # Compaction eligible — look up or generate summary
            summary = await self._get_or_compute_summary(
                raw_text, strategy, curator_model=curator_model,
            )
            if summary is None:
                # Curator failed — pass through unchanged
                new_blocks.append(block)
                continue
            tok_after = _estimate_tokens(summary)
            # Build a marked tool_result block
            new_block = {
                **block,
                "content": (
                    f"[COMPACTED {tok_before}→{tok_after} tokens via "
                    f"{strategy.name}_{STRATEGY_VERSION}]\n{summary}"
                ),
            }
            new_blocks.append(new_block)
            changed = True
            report.compactions.append({
                "strategy": strategy.name,
                "tool_use_id": tool_id,
                "tokens_before": tok_before,
                "tokens_after": tok_after,
            })

        if not changed:
            return msg
        return {**msg, "content": new_blocks}

    def _extract_text(self, block: dict) -> str:
        """Pull raw text from a tool_result block (string or text-block list)."""
        inner = block.get("content")
        if isinstance(inner, str):
            return inner
        if isinstance(inner, list):
            parts = []
            for sub in inner:
                if isinstance(sub, dict) and sub.get("type") == "text":
                    parts.append(sub.get("text") or "")
            return "\n".join(parts)
        return ""

    async def _get_or_compute_summary(
        self,
        raw_text: str,
        strategy: Strategy,
        *,
        curator_model: str | None = None,
    ) -> str | None:
        """Return cached summary if available, else call curator + cache.

        Critical invariant: same raw_text + same strategy + same version
        MUST return identical bytes every call, forever.  This is what
        makes mlx prefix cache still hit after compaction.

        Note: the cache key is intentionally ``(content_hash, strategy,
        version)`` — NOT including ``curator_model``.  Once a summary is
        computed (by whichever curator happened to be chosen that day)
        it's locked in forever.  Different blocks may have been
        summarized by different curators, but each individual block's
        bytes are stable.  This keeps mlx prefix cache stable across
        curator-selection events.
        """
        content_hash = _sha256(raw_text)
        cached = self.cache.get(content_hash, strategy.name)
        if cached is not None:
            return cached

        # Cache miss — call curator (with optional per-call model override)
        user_prompt = strategy.user_prompt_template.format(content=raw_text)
        summary = await self.curator.summarize(
            system=strategy.system_prompt,
            prompt=user_prompt,
            max_tokens=strategy.max_output_tokens,
            model=curator_model,
        )
        if summary is None:
            return None
        # Persist — sticky thereafter
        self.cache.put(
            content_hash=content_hash,
            strategy=strategy.name,
            summary=summary,
            original_tokens=_estimate_tokens(raw_text),
            summary_tokens=_estimate_tokens(summary),
            curator_model=curator_model or getattr(self.curator, "model", "unknown"),
        )
        return summary
