"""Context Hygiene Compactor — shrinks bloated conversation history before
main-model inference, so local LLMs with limited effective-context can still
reason coherently.

Architecture rationale — see `docs/research/...` in the private repo for the
full design doc.  Summary:

  - Local LLMs (e.g. Qwen3-Coder-480B on Mac Studio) have effective agent
    context of ~20-40K tokens before attention degrades.  Hosted Claude
    tolerates much more because Anthropic pays the attention-compute cost.
  - Claude Code CLI tools were designed for hosted-LLM economics:
    ``Read`` dumps whole files, ``Bash`` dumps full stdout, etc.  For
    sessions of 5+ turns this quickly exceeds local effective context.
  - Solution: middleware that replaces bloated ``tool_result`` blocks with
    faithful summaries BEFORE they reach the main model.  Summaries are
    generated by a smaller curator model (e.g. gpt-oss:120b on the same
    fleet), cached by content hash (sticky across sessions), and marked
    explicitly so the agent knows what's compact vs verbatim.

Key invariants — DO NOT VIOLATE:

  1. **Cache stability.** Compacted prefix bytes must be identical across
     requests for the same underlying content, or we bust mlx's prefix
     cache and lose the 10-100× warm-turn speedup.  Enforced via:
       - Content-addressed cache (SHA-256 of raw content → summary)
       - Deterministic curator calls (temperature=0)
       - Sticky summaries (once cached, never regenerated until strategy
         version bumps)

  2. **Never compact cached prefix content.**  System prompt and tool
     definitions are pinned in the prefix cache.  Compacting them would
     bust the cache for every subsequent turn.  Only the message history
     (specifically: old tool_result blocks) is eligible.

  3. **Preserve recency.**  The last N turns (default 3) are passed
     through verbatim.  These are the model's active reasoning context
     and compacting them damages quality.

  4. **Preserve tool_use (assistant side).**  ``tool_use`` blocks inside
     assistant messages are the model's own output; compacting them
     breaks trace continuity and may confuse the agent about its own
     prior decisions.  Only tool RESULTS (the user-role reply that
     follows a tool_use) are compactable.

  5. **Fail open.**  If the curator fails or times out, pass the
     original content through unchanged and log the failure.  Bad
     compaction is worse than no compaction.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import json
import logging
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

logger = logging.getLogger(__name__)


# Strategy version — bump when a strategy's prompt or behavior changes,
# invalidating old cached summaries.  Cache entries under older versions
# become stale and regenerate on next use.
STRATEGY_VERSION = "v1-2026-04-23"


# ----------------------------------------------------------------------------
# Curator interface — pluggable LLM for summary generation
# ----------------------------------------------------------------------------


class CuratorProtocol(Protocol):
    """A callable that takes (prompt_text, max_output_tokens) → summary_text.

    The curator should be deterministic (temperature=0) and fast.
    Implementations should handle their own timeouts and retries.
    """

    async def summarize(
        self, system: str, prompt: str, max_tokens: int = 512, timeout_s: float = 60.0,
    ) -> str | None:
        """Return the summary text, or None on failure/timeout."""
        ...


class OllamaCurator:
    """Curator backed by an Ollama model (e.g. gpt-oss:120b).

    Reuses the herd's existing Ollama client infrastructure.  Uses
    non-streaming chat.  Deterministic via temperature=0.
    """

    def __init__(self, ollama_client, model: str):
        self._ollama = ollama_client
        self.model = model

    async def summarize(
        self, system: str, prompt: str, max_tokens: int = 512, timeout_s: float = 60.0,
    ) -> str | None:
        body = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
            "stream": False,
            "options": {
                "temperature": 0.0,  # determinism for cache stability
                "top_p": 1.0,
                "num_predict": max_tokens,
            },
        }
        try:
            resp = await asyncio.wait_for(self._ollama.chat(body), timeout=timeout_s)
        except TimeoutError:
            logger.warning(f"Curator {self.model} timed out after {timeout_s}s")
            return None
        except Exception as exc:  # noqa: BLE001 — curator failure must fail-open
            logger.warning(f"Curator {self.model} failed: {type(exc).__name__}: {exc}")
            return None
        try:
            return resp["message"]["content"].strip()
        except (KeyError, AttributeError, TypeError):
            logger.warning(f"Curator {self.model} returned unparseable response")
            return None


# ----------------------------------------------------------------------------
# Strategies — content-type-specific compaction prompts
# ----------------------------------------------------------------------------


@dataclass
class Strategy:
    """A compaction strategy: what prompt to send the curator, plus policy."""

    name: str
    system_prompt: str
    user_prompt_template: str  # {content} gets replaced with raw content
    max_output_tokens: int
    # Only compact if the original is larger than this — below, not worth it.
    min_bloat_tokens: int


# Summarize arbitrary file content: preserve identifiers/signatures, drop body.
STRATEGY_READ = Strategy(
    name="read",
    system_prompt=(
        "You are a code summarization assistant.  Another AI needs to know "
        "what's in a file without reading every line.  Extract:\n"
        "  - Public symbols (classes, functions) with their signatures\n"
        "  - Imports and external dependencies\n"
        "  - 1-2 sentences describing the file's purpose\n"
        "  - Any notable constants, patterns, or side effects\n"
        "Preserve EXACTLY: identifier names, file paths, numeric constants, "
        "error message text.  Drop: implementation details, docstrings unless "
        "they add unique info, comments.\n"
        "Respond with the summary only, no preamble."
    ),
    user_prompt_template="File content to summarize:\n\n{content}",
    max_output_tokens=400,
    min_bloat_tokens=1500,
)

# Summarize shell command output: keep first+last lines + exit status.
STRATEGY_BASH = Strategy(
    name="bash",
    system_prompt=(
        "You are summarizing shell command output for another AI.  Keep:\n"
        "  - Exit code (if visible)\n"
        "  - The first 3 lines of output\n"
        "  - The last 3 lines of output\n"
        "  - Any error messages VERBATIM\n"
        "  - Any absolute file paths VERBATIM\n"
        "Drop: repetitive progress lines, log noise, whitespace.\n"
        "Respond with the summary only, no preamble."
    ),
    user_prompt_template="Shell output to summarize:\n\n{content}",
    max_output_tokens=300,
    min_bloat_tokens=800,
)

# Summarize webfetch output (HTML→markdown dump).
STRATEGY_WEBFETCH = Strategy(
    name="webfetch",
    system_prompt=(
        "You are summarizing a web page's content for another AI.  Extract:\n"
        "  - Main topic (1 sentence)\n"
        "  - Key facts, figures, identifiers\n"
        "  - Any code snippets VERBATIM\n"
        "  - URLs referenced\n"
        "Drop: navigation, ads, boilerplate, formatting fluff.\n"
        "Respond with the summary only, no preamble."
    ),
    user_prompt_template="Web page content to summarize:\n\n{content}",
    max_output_tokens=500,
    min_bloat_tokens=2000,
)


# Map from tool name → strategy.  Tools not listed pass through verbatim.
STRATEGIES_BY_TOOL: dict[str, Strategy] = {
    "Read": STRATEGY_READ,
    "Bash": STRATEGY_BASH,
    "WebFetch": STRATEGY_WEBFETCH,
}


# ----------------------------------------------------------------------------
# Summary cache — content-addressed, persistent across sessions
# ----------------------------------------------------------------------------


class SummaryCache:
    """SQLite-backed content-addressed summary cache.

    Key: (content_sha256, strategy_name, strategy_version).  Returning
    the SAME summary bytes for the SAME input content is what preserves
    mlx prefix-cache stability across sessions.

    Thread-safe for concurrent reads; writes are single-threaded via
    a connection-per-call pattern (SQLite's default-serialized mode).
    """

    def __init__(self, db_path: Path):
        self.db_path = db_path
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    def _conn(self) -> sqlite3.Connection:
        c = sqlite3.connect(self.db_path, timeout=5.0)
        c.row_factory = sqlite3.Row
        return c

    def _init_schema(self) -> None:
        with self._conn() as c:
            c.execute("""
                CREATE TABLE IF NOT EXISTS summaries (
                    content_hash TEXT NOT NULL,
                    strategy TEXT NOT NULL,
                    strategy_version TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    original_tokens INTEGER NOT NULL,
                    summary_tokens INTEGER NOT NULL,
                    curator_model TEXT NOT NULL,
                    created_at REAL NOT NULL,
                    hit_count INTEGER NOT NULL DEFAULT 0,
                    PRIMARY KEY (content_hash, strategy, strategy_version)
                )
            """)
            c.execute("""
                CREATE INDEX IF NOT EXISTS idx_summaries_created_at
                ON summaries(created_at)
            """)

    def get(
        self, content_hash: str, strategy: str, version: str = STRATEGY_VERSION,
    ) -> str | None:
        with self._conn() as c:
            row = c.execute(
                "SELECT summary FROM summaries "
                "WHERE content_hash = ? AND strategy = ? AND strategy_version = ?",
                (content_hash, strategy, version),
            ).fetchone()
            if row is None:
                return None
            # Bump hit count (best-effort; don't block caller on failure)
            with contextlib.suppress(sqlite3.OperationalError):
                c.execute(
                    "UPDATE summaries SET hit_count = hit_count + 1 "
                    "WHERE content_hash = ? AND strategy = ? AND strategy_version = ?",
                    (content_hash, strategy, version),
                )
            return row["summary"]

    def put(
        self,
        content_hash: str,
        strategy: str,
        summary: str,
        original_tokens: int,
        summary_tokens: int,
        curator_model: str,
        version: str = STRATEGY_VERSION,
    ) -> None:
        with self._conn() as c:
            c.execute(
                "INSERT OR REPLACE INTO summaries "
                "(content_hash, strategy, strategy_version, summary, "
                "original_tokens, summary_tokens, curator_model, created_at, hit_count) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)",
                (
                    content_hash, strategy, version, summary,
                    original_tokens, summary_tokens, curator_model, time.time(),
                ),
            )

    def stats(self) -> dict:
        """Cache size / hit distribution for dashboard exposure."""
        with self._conn() as c:
            row = c.execute(
                "SELECT COUNT(*) as n_entries, "
                "SUM(original_tokens) as total_original, "
                "SUM(summary_tokens) as total_summary, "
                "SUM(hit_count) as total_hits "
                "FROM summaries"
            ).fetchone()
            return {
                "entries": row["n_entries"] or 0,
                "total_original_tokens": row["total_original"] or 0,
                "total_summary_tokens": row["total_summary"] or 0,
                "total_hits": row["total_hits"] or 0,
            }


# ----------------------------------------------------------------------------
# Compactor — the main entry point
# ----------------------------------------------------------------------------


@dataclass
class CompactionReport:
    """What the compactor did on a single request.  Flows into traces."""

    triggered: bool = False
    tokens_before: int = 0
    tokens_after: int = 0
    compactions: list[dict] = field(default_factory=list)

    @property
    def ratio(self) -> float:
        if not self.tokens_before:
            return 1.0
        return self.tokens_after / self.tokens_before

    def to_dict(self) -> dict:
        return {
            "triggered": self.triggered,
            "tokens_before": self.tokens_before,
            "tokens_after": self.tokens_after,
            "ratio": round(self.ratio, 3),
            "compactions": list(self.compactions),
        }


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def _estimate_tokens(text: str) -> int:
    """Rough: 4 chars/token.  Good enough for budget decisions."""
    return max(1, len(text) // 4)


class ContextCompactor:
    """Server-side middleware that shrinks bloated conversation history.

    Stateless across requests except for the SummaryCache.  Safe to
    share a single instance across all requests — internal caching is
    SQLite-backed and thread-safe.
    """

    def __init__(
        self,
        curator: CuratorProtocol,
        cache: SummaryCache,
        *,
        budget_tokens: int = 20_000,
        preserve_last_turns: int = 3,
    ):
        self.curator = curator
        self.cache = cache
        self.budget_tokens = budget_tokens
        self.preserve_last_turns = preserve_last_turns

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def maybe_compact(
        self, messages: list[dict],
    ) -> tuple[list[dict], CompactionReport]:
        """Compact messages if they exceed the budget; otherwise pass through.

        Input: Anthropic-format messages (content may be string or block list).
        Output: (possibly-modified messages, report).

        Does NOT modify the input list in place.
        """
        report = CompactionReport()
        report.tokens_before = self._total_tokens(messages)

        if report.tokens_before <= self.budget_tokens:
            report.tokens_after = report.tokens_before
            return messages, report

        # Build a map of tool_use_id → tool_name by scanning assistant
        # messages.  Needed to classify tool_result blocks.
        tool_use_names = self._index_tool_uses(messages)

        # Identify which messages are eligible (preserve the last N turns).
        n_total = len(messages)
        preserved_start = max(0, n_total - self.preserve_last_turns * 2)
        # * 2 because each turn is user+assistant on average

        report.triggered = True
        out_messages: list[dict] = []

        for i, msg in enumerate(messages):
            if i >= preserved_start:
                # Preserve verbatim — recent turns
                out_messages.append(msg)
                continue
            # Compactable range: look at content blocks for tool_results
            new_msg = await self._compact_message(msg, tool_use_names, report)
            out_messages.append(new_msg)

        report.tokens_after = self._total_tokens(out_messages)
        return out_messages, report

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _index_tool_uses(self, messages: list[dict]) -> dict[str, str]:
        """Walk messages, return {tool_use_id → tool_name} map."""
        out: dict[str, str] = {}
        for m in messages:
            if m.get("role") != "assistant":
                continue
            c = m.get("content")
            if not isinstance(c, list):
                continue
            for block in c:
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    tool_id = block.get("id")
                    tool_name = block.get("name")
                    if tool_id and tool_name:
                        out[tool_id] = tool_name
        return out

    def _total_tokens(self, messages: list[dict]) -> int:
        """Estimate total tokens across all messages."""
        total = 0
        for m in messages:
            c = m.get("content")
            if isinstance(c, str):
                total += _estimate_tokens(c)
            elif isinstance(c, list):
                for block in c:
                    if not isinstance(block, dict):
                        continue
                    if block.get("type") == "text":
                        total += _estimate_tokens(block.get("text") or "")
                    elif block.get("type") == "tool_use":
                        total += _estimate_tokens(
                            json.dumps(block.get("input") or {})
                        )
                    elif block.get("type") == "tool_result":
                        inner = block.get("content")
                        if isinstance(inner, str):
                            total += _estimate_tokens(inner)
                        elif isinstance(inner, list):
                            for sub in inner:
                                if (
                                    isinstance(sub, dict)
                                    and sub.get("type") == "text"
                                ):
                                    total += _estimate_tokens(sub.get("text") or "")
        return total

    async def _compact_message(
        self,
        msg: dict,
        tool_use_names: dict[str, str],
        report: CompactionReport,
    ) -> dict:
        """Walk a message's content blocks, compact tool_results if eligible."""
        content = msg.get("content")
        if not isinstance(content, list):
            return msg  # string content or unknown — pass through

        new_blocks: list[dict] = []
        changed = False
        for block in content:
            if (
                not isinstance(block, dict)
                or block.get("type") != "tool_result"
            ):
                new_blocks.append(block)
                continue
            # Classify via the corresponding tool_use
            tool_id = block.get("tool_use_id")
            tool_name = tool_use_names.get(tool_id or "")
            strategy = STRATEGIES_BY_TOOL.get(tool_name or "")
            if strategy is None:
                new_blocks.append(block)
                continue
            # Extract text payload
            raw_text = self._extract_text(block)
            if not raw_text:
                new_blocks.append(block)
                continue
            tok_before = _estimate_tokens(raw_text)
            if tok_before < strategy.min_bloat_tokens:
                new_blocks.append(block)
                continue
            # Compaction eligible — look up or generate summary
            summary = await self._get_or_compute_summary(raw_text, strategy)
            if summary is None:
                # Curator failed — pass through unchanged
                new_blocks.append(block)
                continue
            tok_after = _estimate_tokens(summary)
            # Build a marked tool_result block
            new_block = {
                **block,
                "content": (
                    f"[COMPACTED {tok_before}→{tok_after} tokens via "
                    f"{strategy.name}_{STRATEGY_VERSION}]\n{summary}"
                ),
            }
            new_blocks.append(new_block)
            changed = True
            report.compactions.append({
                "strategy": strategy.name,
                "tool_use_id": tool_id,
                "tokens_before": tok_before,
                "tokens_after": tok_after,
            })

        if not changed:
            return msg
        return {**msg, "content": new_blocks}

    def _extract_text(self, block: dict) -> str:
        """Pull raw text from a tool_result block (string or text-block list)."""
        inner = block.get("content")
        if isinstance(inner, str):
            return inner
        if isinstance(inner, list):
            parts = []
            for sub in inner:
                if isinstance(sub, dict) and sub.get("type") == "text":
                    parts.append(sub.get("text") or "")
            return "\n".join(parts)
        return ""

    async def _get_or_compute_summary(
        self, raw_text: str, strategy: Strategy,
    ) -> str | None:
        """Return cached summary if available, else call curator + cache.

        Critical invariant: same raw_text + same strategy + same version
        MUST return identical bytes every call, forever.  This is what
        makes mlx prefix cache still hit after compaction.
        """
        content_hash = _sha256(raw_text)
        cached = self.cache.get(content_hash, strategy.name)
        if cached is not None:
            return cached

        # Cache miss — call curator
        user_prompt = strategy.user_prompt_template.format(content=raw_text)
        summary = await self.curator.summarize(
            system=strategy.system_prompt,
            prompt=user_prompt,
            max_tokens=strategy.max_output_tokens,
        )
        if summary is None:
            return None
        # Persist — sticky thereafter
        self.cache.put(
            content_hash=content_hash,
            strategy=strategy.name,
            summary=summary,
            original_tokens=_estimate_tokens(raw_text),
            summary_tokens=_estimate_tokens(summary),
            curator_model=getattr(self.curator, "model", "unknown"),
        )
        return summary
